// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"

	"gitlab.com/hmajid2301/gofeedback/internal/transport/http/views/icons"
)

func Features() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"features\" class=\"py-16 bg-base-100\"><div class=\"container px-4 mx-auto\"><h2 class=\"mb-12 text-4xl font-bold text-center\">Why Choose Go Feedback?</h2><div class=\"grid gap-8 md:grid-cols-2 lg:grid-cols-3\"><!-- Feedback Prioritization --><div class=\"p-6 rounded-lg transition-all hover:shadow-xl hover:scale-105 text-neutral bg-base-300\"><div class=\"text-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.HeartCheck("mb-4 w-16 h-auto text-red-600 mx-auto").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<h3 class=\"mb-3 text-xl font-semibold\">Feedback Prioritization</h3><p class=\"text-sm\">Automated voting system surfaces top requests through user upvotes and engagement tracking.</p></div></div><!-- Board Visibility --><div class=\"p-6 rounded-lg transition-all hover:shadow-xl hover:scale-105 text-neutral bg-base-300\"><div class=\"text-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Clipboard("mb-4 w-16 h-auto text-teal-600 mx-auto").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<h3 class=\"mb-3 text-xl font-semibold\">Board Visibility</h3><p class=\"text-sm\">Public community boards and private internal roadmaps with granular access controls.</p></div></div><!-- AI Insights --><div class=\"p-6 rounded-lg transition-all hover:shadow-xl hover:scale-105 text-neutral bg-base-300\"><div class=\"text-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.AIBrain("mb-4 w-16 h-auto text-emerald-600 mx-auto").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<h3 class=\"mb-3 text-xl font-semibold\">AI Insights</h3><p class=\"text-sm\">Automatic review aggregation from 15+ platforms with sentiment analysis.</p></div></div><!-- API & Integrations --><div class=\"p-6 rounded-lg transition-all hover:shadow-xl hover:scale-105 text-neutral bg-base-300\"><div class=\"text-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Puzzle("mb-4 w-16 h-auto text-amber-600 mx-auto").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<h3 class=\"mb-3 text-xl font-semibold\">API & Integrations</h3><p class=\"text-sm\">Connect with Zapier, Intercom, and custom webhooks with real-time sync.</p></div></div><!-- Premium Voting --><div class=\"p-6 rounded-lg transition-all hover:shadow-xl hover:scale-105 text-neutral bg-base-300\"><div class=\"text-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Diamond("mb-4 w-16 h-auto text-yellow-600 mx-auto").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<h3 class=\"mb-3 text-xl font-semibold\">Premium Voting</h3><p class=\"text-sm\">Paid plans can get added voting weight, added to betas, and private voting lanes.</p></div></div><!-- Moderation Suite --><div class=\"p-6 rounded-lg transition-all hover:shadow-xl hover:scale-105 text-neutral bg-base-300\"><div class=\"text-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Shield("mb-4 w-16 h-auto text-orange-600 mx-auto").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<h3 class=\"mb-3 text-xl font-semibold\">Moderation Suite</h3><p class=\"text-sm\">AI-powered content filtering with custom rules and approval workflows.</p></div></div><!-- White Label --><div class=\"p-6 rounded-lg transition-all hover:shadow-xl hover:scale-105 text-neutral bg-base-300\"><div class=\"text-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.PaintRoller("mb-4 w-16 h-auto text-purple-600 mx-auto").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<h3 class=\"mb-3 text-xl font-semibold\">White Label</h3><p class=\"text-sm\">Custom domains, CSS variables, and complete branding control.</p></div></div><!-- Knowledge Base --><div class=\"p-6 rounded-lg transition-all hover:shadow-xl hover:scale-105 text-neutral bg-base-300\"><div class=\"text-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Book("mb-4 w-16 h-auto text-indigo-600 mx-auto").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<h3 class=\"mb-3 text-xl font-semibold\">Knowledge Base</h3><p class=\"text-sm\">Smart search with AI suggestions and article feedback tracking.</p></div></div><!-- User SSO --><div class=\"p-6 rounded-lg transition-all hover:shadow-xl hover:scale-105 text-neutral bg-base-300\"><div class=\"text-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Lock("mb-4 w-16 h-auto text-pink-600 mx-auto").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<h3 class=\"mb-3 text-xl font-semibold\">User SSO</h3><p class=\"text-sm\">Use your own auth, users can sign up automatically.</p></div></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
