// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

func Footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<footer class=\"p-10 footer bg-neutral text-neutral-content sm:footer-horizontal\"><nav><h6 class=\"footer-title\">Company</h6><a class=\"link link-hover\">About us</a> <a class=\"link link-hover\">Contact</a></nav><nav><h6 class=\"footer-title\">Legal</h6><a href=\"/terms\" class=\"link link-hover\">Terms of service</a> <a href=\"/privacy\" class=\"link link-hover\">Privacy policy</a> <a href=\"/eula\" class=\"link link-hover\">EULA</a> <a href=\"/refund\" class=\"link link-hover\">Refund</a> <a href=\"/cookie\" class=\"link link-hover\">Cookie</a></nav><nav><h6 class=\"footer-title\">Featured On</h6><a href=\"https://twelve.tools\" target=\"_blank\"><img src=\"https://twelve.tools/badge0-light.svg\" alt=\"Featured on Twelve Tools\" width=\"200\" height=\"50\"></a> <a href=\"https://indievoice.app\" target=\"_blank\"><img src=\"https://1f08bbd99d1a620c734d44a7ea6c9651.cdn.bubble.io/f1732389057276x672158288395191600/featured.png\" alt=\"IndieVoice Embed Badge\" width=\"200\" height=\"50\" style=\"image-rendering: -webkit-optimize-contrast; image-rendering: crisp-edges;\"></a> <a href=\"https://startupfa.me/s/go-feedback?utm_source=gofeedback.app\" target=\"_blank\"><img src=\"https://startupfa.me/badges/featured-badge.webp\" alt=\"Go Feedback - Transform user feedback into product gold | Startup Fame\" width=\"200\" height=\"50\"></a></nav></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
