// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"

	"gitlab.com/hmajid2301/gofeedback/internal/transport/http/views/icons"
)

func Pricing() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"pricing\" class=\"py-16 bg-syncwave-background\"><div class=\"container px-4 mx-auto\"><h2 class=\"mb-12 text-4xl font-bold text-center text-syncwave-text\">Straight forward Pricing for Every Stage</h2><div class=\"grid gap-8 md:grid-cols-3\"><!-- Free Tier --><div class=\"p-6 rounded-lg border shadow-md transition-all hover:shadow-xl hover:scale-105 bg-slate-800 border-slate-700\"><h3 class=\"mb-4 text-2xl font-semibold text-syncwave-text\">Free</h3><p class=\"mb-4 text-3xl font-bold text-syncwave-accent\">$0<span class=\"text-xl text-slate-400\">/month</span></p><ul class=\"mb-6 space-y-3\"><li class=\"flex items-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Tick("mr-2 w-8 h-auto text-emerald-400").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<span class=\"text-slate-400\">Up to 100 users</span></li><li class=\"flex items-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Tick("mr-2 w-8 h-auto text-emerald-400").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<span class=\"text-slate-400\">Basic feedback collection</span></li><li class=\"flex items-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Tick("mr-2 w-8 h-auto text-emerald-400").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<span class=\"text-slate-400\">Public roadmap</span></li></ul><a href=\"#\" class=\"block py-3 px-4 w-full text-center rounded-lg border-2 transition-colors border-syncwave-accent text-syncwave-accent hover:bg-slate-800\">Get Started</a></div><!-- Startup Tier (Highlighted) --><div class=\"p-6 rounded-lg border-2 shadow-xl transition-all hover:scale-105 bg-slate-800 border-syncwave-accent\"><div class=\"mb-2\"><span class=\"py-1 px-3 text-sm font-bold rounded-full bg-syncwave-accent text-slate-900\">Most Popular</span></div><h3 class=\"mb-4 text-2xl font-semibold text-syncwave-text\">Startup</h3><p class=\"mb-4 text-3xl font-bold text-syncwave-accent\">$29<span class=\"text-xl text-slate-400\">/month</span></p><ul class=\"mb-6 space-y-3\"><li class=\"flex items-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Tick("mr-2 w-8 h-auto text-emerald-400").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<span class=\"text-slate-400\">Up to 500 users</span></li><li class=\"flex items-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Tick("mr-2 w-8 h-auto text-emerald-400").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<span class=\"text-slate-400\">Advanced analytics</span></li><li class=\"flex items-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Tick("mr-2 w-8 h-auto text-emerald-400").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<span class=\"text-slate-400\">Custom branding</span></li></ul><a href=\"#\" class=\"block py-3 px-4 w-full text-center rounded-lg transition-colors hover:bg-blue-400 bg-syncwave-accent text-slate-900\">Choose Startup</a></div><!-- Pro Tier --><div class=\"p-6 rounded-lg border shadow-md transition-all hover:shadow-xl hover:scale-105 bg-slate-800 border-slate-700\"><h3 class=\"mb-4 text-2xl font-semibold text-syncwave-text\">Pro</h3><p class=\"mb-4 text-3xl font-bold text-syncwave-accent\">$99<span class=\"text-xl text-slate-400\">/month</span></p><ul class=\"mb-6 space-y-3\"><li class=\"flex items-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Tick("mr-2 w-8 h-auto text-emerald-400").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<span class=\"text-slate-400\">Unlimited users</span></li><li class=\"flex items-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Tick("mr-2 w-8 h-auto text-emerald-400").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<span class=\"text-slate-400\">Dedicated support</span></li><li class=\"flex items-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Tick("mr-2 w-8 h-auto text-emerald-400").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<span class=\"text-slate-400\">Advanced security</span></li></ul><a href=\"#\" class=\"block py-3 px-4 w-full text-center rounded-lg transition-colors hover:bg-blue-400 bg-syncwave-accent text-slate-900\">Choose Pro</a></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
