// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddExample(ctx context.Context, id uuid.UUID) (Example, error)
	GetExample(ctx context.Context, id uuid.UUID) (Example, error)
}

var _ Querier = (*Queries)(nil)
