// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addExample = `-- name: AddExample :one
INSERT INTO example (id) VALUES ($1) RETURNING *;
`

func (q *Queries) AddExample(ctx context.Context, id uuid.UUID) (Example, error) {
	row := q.db.QueryRow(ctx, addExample, id)
	var i Example
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Fields,
	)
	return i, err
}
